 INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'The Kite Runner',
'Khaled Hosseini',
'Fiction',
'A deeply emotional novel set against the backdrop of Afghanistan’s turbulent history. It follows Amir, a privileged boy haunted by guilt over betraying his closest friend, Hassan. The story explores friendship, betrayal, redemption, and the enduring impact of childhood choices.',
'9781594631931'),

(gen_random_uuid(),
'A Thousand Splendid Suns',
'Khaled Hosseini',
'Fiction',
'Spanning three decades, this novel tells the intertwined stories of Mariam and Laila, two women bound together by marriage and circumstance. Set in Afghanistan, it portrays resilience, sacrifice, and the quiet strength of women enduring war and oppression.',
'9781594631726'),

 

(gen_random_uuid(),
'The Book Thief',
'Markus Zusak',
'Fiction',
'Narrated by Death, this novel follows Liesel, a young girl growing up in Nazi Germany who finds solace in stealing books. It is a powerful meditation on humanity, cruelty, love, and the redemptive power of words.',
'9780375842207'),

(gen_random_uuid(),
'The Road',
'Cormac McCarthy',
'Fiction',
'A bleak yet tender post-apocalyptic novel about a father and son traveling through a devastated world. The story examines survival, morality, and unconditional love in the face of utter despair.',
'9780307387899'),

(gen_random_uuid(),
'The Curious Incident of the Dog in the Night-Time',
'Mark Haddon',
'Fiction',
'Told from the perspective of a teenage boy on the autism spectrum, this novel blends mystery and emotional depth. It explores logic, trust, family relationships, and the struggle to understand human emotions.',
'9781400032716'),

(gen_random_uuid(),
'Gone Girl',
'Gillian Flynn',
'Fiction',
'A psychological novel about a marriage gone terribly wrong when a woman disappears on her anniversary. With unreliable narrators and sharp social commentary, it examines manipulation, media, and identity.',
'9780307588371'),

(gen_random_uuid(),
'The Night Circus',
'Erin Morgenstern',
'Fiction',
'A magical realist novel centered on a mysterious circus that appears without warning. Behind the spectacle lies a dangerous competition between two illusionists, blending romance, fantasy, and fate.',
'9780307744432'),

(gen_random_uuid(),
'Little Fires Everywhere',
'Celeste Ng',
'Fiction',
'A suburban drama that explores motherhood, identity, privilege, and secrets. When two families collide, long-buried tensions surface, revealing how small choices can ignite lasting consequences.',
'9780735224292'),

(gen_random_uuid(),
'The Goldfinch',
'Donna Tartt',
'Fiction',
'A sweeping novel following a boy whose life changes after surviving a museum bombing. The story explores loss, obsession, art, and the long shadow of trauma.',
'9780316055437'),

(gen_random_uuid(),
'Shantaram',
'Gregory David Roberts',
'Fiction',
'Based on the author’s life, this novel follows an escaped convict living in the underworld of Bombay. It is an epic story of crime, spirituality, love, and redemption.',
'9780312330538'),

(gen_random_uuid(),
'The Shadow of the Wind',
'Carlos Ruiz Zafón',
'Fiction',
'A literary mystery set in post-war Barcelona, where a young boy discovers a forgotten book that leads him into a labyrinth of secrets, love, and vengeance.',
'9780143034902'),

(gen_random_uuid(),
'The Help',
'Kathryn Stockett',
'Fiction',
'Set in 1960s Mississippi, this novel tells the stories of African American maids and the white women they work for. It confronts racism, courage, and social change.',
'9780425232200'),

(gen_random_uuid(),
'The Alchemist',
'Paulo Coelho',
'Fiction',
'A philosophical tale about a shepherd named Santiago who travels in search of treasure. The novel emphasizes destiny, dreams, and listening to one’s heart.',
'9780062315007'),

(gen_random_uuid(),
'Never Let Me Go',
'Kazuo Ishiguro',
'Fiction',
'A haunting dystopian novel that slowly reveals a dark truth about its characters’ existence. It explores memory, love, and what it means to be human.',
'9781400078776'),

(gen_random_uuid(),
'The Lovely Bones',
'Alice Sebold',
'Fiction',
'Narrated by a murdered teenage girl, this novel explores grief, healing, and the impact of loss on a family and community.',
'9780316168816'),

(gen_random_uuid(),
'Cloud Atlas',
'David Mitchell',
'Fiction',
'A complex, interconnected novel spanning centuries and genres. It examines how actions echo through time and how humanity repeats patterns of power and resistance.',
'9780375507250'),

(gen_random_uuid(),
'Station Eleven',
'Emily St. John Mandel',
'Fiction',
'A post-pandemic novel that follows interconnected characters before and after a global collapse. It reflects on art, memory, and survival.',
'9780804172448'),

(gen_random_uuid(),
'The Time Traveler’s Wife',
'Audrey Niffenegger',
'Fiction',
'A love story complicated by involuntary time travel. The novel explores fate, loss, and enduring emotional bonds.',
'9780156029438'),

(gen_random_uuid(),
'White Teeth',
'Zadie Smith',
'Fiction',
'A multigenerational novel about immigration, identity, and cultural conflict in modern London, blending humor with sharp social insight.',
'9780375703867');
INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'The Hobbit',
'J.R.R. Tolkien',
'Fantasy',
'A classic fantasy novel about Bilbo Baggins, a reluctant hobbit who embarks on an adventure filled with dragons, dwarves, and danger. It is a tale of courage and transformation.',
'9780547928227'),

(gen_random_uuid(),
'A Game of Thrones',
'George R.R. Martin',
'Fantasy',
'The first book in A Song of Ice and Fire, depicting political intrigue, war, and power struggles across the Seven Kingdoms.',
'9780553593716'),

(gen_random_uuid(),
'The Name of the Wind',
'Patrick Rothfuss',
'Fantasy',
'A richly told story of Kvothe, a gifted young man who grows into a legendary figure. It blends magic, music, and myth.',
'9780756404741'),

(gen_random_uuid(),
'Mistborn: The Final Empire',
'Brandon Sanderson',
'Fantasy',
'A unique fantasy world where magic is derived from metals. The story follows a rebellion against a tyrannical ruler.',
'9780765311788'),

(gen_random_uuid(),
'The Fellowship of the Ring',
'J.R.R. Tolkien',
'Fantasy',
'The first volume of The Lord of the Rings, following Frodo’s journey to destroy a powerful and dangerous ring.',
'9780547928210'),

(gen_random_uuid(),
'The Lion, the Witch and the Wardrobe',
'C.S. Lewis',
'Fantasy',
'Four siblings discover a magical land ruled by an evil queen. A timeless story of courage, sacrifice, and hope.',
'9780064471046'),

(gen_random_uuid(),
'American Gods',
'Neil Gaiman',
'Fantasy',
'A modern fantasy where ancient gods struggle to survive in contemporary America. It blends mythology with road-trip storytelling.',
'9780062572233'),

(gen_random_uuid(),
'The Way of Kings',
'Brandon Sanderson',
'Fantasy',
'An epic fantasy novel set in a storm-ravaged world, exploring leadership, honor, and destiny.',
'9780765326355'),

(gen_random_uuid(),
'Good Omens',
'Neil Gaiman & Terry Pratchett',
'Fantasy',
'A humorous fantasy about an angel and a demon trying to prevent the apocalypse.',
'9780060853983'),

(gen_random_uuid(),
'Eragon',
'Christopher Paolini',
'Fantasy',
'A farm boy discovers a dragon egg, setting him on a path toward destiny, magic, and war.',
'9780375826696'),

(gen_random_uuid(),
'The Magicians',
'Lev Grossman',
'Fantasy',
'A darker take on magical education, following students who discover magic is real and dangerous.',
'9780452296299'),

(gen_random_uuid(),
'The Once and Future King',
'T.H. White',
'Fantasy',
'A retelling of the Arthurian legends, focusing on power, justice, and human flaws.',
'9780441627400'),

(gen_random_uuid(),
'His Dark Materials: Northern Lights',
'Philip Pullman',
'Fantasy',
'A young girl’s journey through parallel worlds, challenging authority and destiny.',
'9780440418320'),

(gen_random_uuid(),
'The Sword of Shannara',
'Terry Brooks',
'Fantasy',
'A classic high fantasy about magic, prophecy, and a battle against ancient evil.',
'9780345314253'),

(gen_random_uuid(),
'The Last Unicorn',
'Peter S. Beagle',
'Fantasy',
'A lyrical fantasy about a unicorn searching for others of her kind, exploring loss and immortality.',
'9780451450524');
INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'1984',
'George Orwell',
'Classic',
'A dystopian novel depicting a totalitarian state that controls truth and individual freedom.',
'9780451524935'),

(gen_random_uuid(),
'To Kill a Mockingbird',
'Harper Lee',
'Classic',
'A powerful story about racial injustice and moral growth in the American South.',
'9780061120084'),

(gen_random_uuid(),
'Pride and Prejudice',
'Jane Austen',
'Classic',
'A romantic and social commentary on class, marriage, and morality in 19th century England.',
'9780141439518'),

(gen_random_uuid(),
'The Great Gatsby',
'F. Scott Fitzgerald',
'Classic',
'A critique of the American Dream through wealth, love, and illusion.',
'9780743273565'),

(gen_random_uuid(),
'Moby Dick',
'Herman Melville',
'Classic',
'An epic tale of obsession and revenge between man and whale.',
'9781503280786'),

(gen_random_uuid(),
'Crime and Punishment',
'Fyodor Dostoevsky',
'Classic',
'A psychological exploration of guilt, morality, and redemption.',
'9780140449136'),

(gen_random_uuid(),
'Wuthering Heights',
'Emily Brontë',
'Classic',
'A dark romance driven by passion and revenge on the Yorkshire moors.',
'9780141439556'),

(gen_random_uuid(),
'Jane Eyre',
'Charlotte Brontë',
'Classic',
'A novel about independence, morality, and love.',
'9780141441146'),

(gen_random_uuid(),
'The Catcher in the Rye',
'J.D. Salinger',
'Classic',
'A teenage boy’s critique of adult hypocrisy and alienation.',
'9780316769488'),

(gen_random_uuid(),
'The Odyssey',
'Homer',
'Classic',
'An epic poem recounting Odysseus’s long journey home.',
'9780140268867'),

(gen_random_uuid(),
'Brave New World',
'Aldous Huxley',
'Classic',
'A dystopian vision of a technologically controlled society.',
'9780060850524'),

(gen_random_uuid(),
'Fahrenheit 451',
'Ray Bradbury',
'Classic',
'A future where books are banned and burned.',
'9781451673319'),

(gen_random_uuid(),
'The Picture of Dorian Gray',
'Oscar Wilde',
'Classic',
'A tale of vanity, corruption, and eternal youth.',
'9780141439570'),

(gen_random_uuid(),
'Anna Karenina',
'Leo Tolstoy',
'Classic',
'A tragic story of love and society in imperial Russia.',
'9780143035008'),

(gen_random_uuid(),
'Les Misérables',
'Victor Hugo',
'Classic',
'An epic novel of justice, redemption, and revolution.',
'9780451419439');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'The Girl with the Dragon Tattoo',
'Stieg Larsson',
'Thriller',
'A gripping crime thriller involving a journalist and a brilliant hacker investigating a decades-old disappearance tied to a powerful Swedish family. The novel blends mystery, corruption, abuse, and investigative journalism.',
'9780307454546'),

(gen_random_uuid(),
'The Da Vinci Code',
'Dan Brown',
'Thriller',
'A fast-paced thriller that follows symbologist Robert Langdon as he uncovers religious secrets hidden in art and history. The novel explores conspiracy, faith, and hidden truths.',
'9780307474278'),

(gen_random_uuid(),
'Gone Girl',
'Gillian Flynn',
'Thriller',
'A dark psychological thriller about a marriage that turns toxic after a wife mysteriously disappears. Media manipulation, deception, and unreliable narration drive the tension.',
'9780307588371'),

(gen_random_uuid(),
'The Silence of the Lambs',
'Thomas Harris',
'Thriller',
'An FBI trainee seeks the help of a brilliant but terrifying serial killer to catch another murderer. The novel explores psychological manipulation and criminal profiling.',
'9780312924584'),

(gen_random_uuid(),
'The Reversal',
'Michael Connelly',
'Thriller',
'A legal thriller featuring Mickey Haller as he prosecutes a high-profile case involving a convicted child killer. The story explores justice, ethics, and legal strategy.',
'9780316069427'),

(gen_random_uuid(),
'Big Little Lies',
'Liane Moriarty',
'Thriller',
'What begins as a school trivia night ends in murder. The novel uncovers secrets, domestic abuse, and lies hidden behind perfect suburban lives.',
'9780399167065'),

(gen_random_uuid(),
'The Woman in the Window',
'A.J. Finn',
'Thriller',
'A psychological thriller about an agoraphobic woman who believes she has witnessed a crime. Reality and delusion blur dangerously.',
'9780062678416'),

(gen_random_uuid(),
'Before I Go to Sleep',
'S.J. Watson',
'Thriller',
'A woman with no memory of her past wakes up every day with her life erased. A shocking truth slowly emerges.',
'9780062060556'),

(gen_random_uuid(),
'The Bourne Identity',
'Robert Ludlum',
'Thriller',
'A man with no memory discovers he is a trained assassin and must uncover his identity while being hunted.',
'9780553283204'),

(gen_random_uuid(),
'Shutter Island',
'Dennis Lehane',
'Thriller',
'U.S. marshals investigate a disappearance at a mental institution, uncovering disturbing truths about reality and identity.',
'9780060835392'),

(gen_random_uuid(),
'The Pelican Brief',
'John Grisham',
'Thriller',
'A law student uncovers a conspiracy involving the assassination of Supreme Court justices.',
'9780440245926'),

(gen_random_uuid(),
'The Girl on the Train',
'Paula Hawkins',
'Thriller',
'A psychological thriller told through the eyes of an unreliable narrator who becomes entangled in a missing-person case.',
'9781594633669'),

(gen_random_uuid(),
'Angels & Demons',
'Dan Brown',
'Thriller',
'A secret society threatens the Vatican, forcing a race against time involving science and religion.',
'9780743493461'),

(gen_random_uuid(),
'The Firm',
'John Grisham',
'Thriller',
'A young lawyer joins a prestigious firm only to discover it is run by organized crime.',
'9780440245925'),

(gen_random_uuid(),
'Sharp Objects',
'Gillian Flynn',
'Thriller',
'A journalist returns to her hometown to investigate murders while confronting her traumatic past.',
'9780307341556'),

(gen_random_uuid(),
'Dark Places',
'Gillian Flynn',
'Thriller',
'A woman revisits the massacre of her family to uncover buried truths.',
'9780307341570'),

(gen_random_uuid(),
'The Snowman',
'Jo Nesbø',
'Thriller',
'A serial killer leaves snowmen as calling cards. Detective Harry Hole races to stop him.',
'9780307473660'),

(gen_random_uuid(),
'Inferno',
'Dan Brown',
'Thriller',
'Robert Langdon races across Europe to stop a global catastrophe linked to Dante’s Inferno.',
'9780804172264'),

(gen_random_uuid(),
'The Girl Who Played with Fire',
'Stieg Larsson',
'Thriller',
'The second book in the Millennium series, deepening the mystery around Lisbeth Salander.',
'9780307454553'),

(gen_random_uuid(),
'The Lincoln Lawyer',
'Michael Connelly',
'Thriller',
'A defense attorney works cases from his car while navigating dangerous legal territory.',
'9780446618328');
INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Me Before You',
'Jojo Moyes',
'Romance',
'A heartfelt love story between a young woman and a man left paralyzed after an accident, exploring love, choice, and dignity.',
'9780143124542'),

(gen_random_uuid(),
'The Notebook',
'Nicholas Sparks',
'Romance',
'A timeless love story about enduring devotion and memory.',
'9780446605236'),

(gen_random_uuid(),
'Pride and Prejudice',
'Jane Austen',
'Romance',
'A classic romance exploring love, class, and misunderstandings.',
'9780141439518'),

(gen_random_uuid(),
'Outlander',
'Diana Gabaldon',
'Romance',
'A time-travel romance set between 20th-century Scotland and the 1700s.',
'9780440212560'),

(gen_random_uuid(),
'It Ends with Us',
'Colleen Hoover',
'Romance',
'A modern romance addressing love, abuse, and difficult choices.',
'9781501110368'),

(gen_random_uuid(),
'The Time Traveler’s Wife',
'Audrey Niffenegger',
'Romance',
'A love story complicated by involuntary time travel.',
'9780156029438'),

(gen_random_uuid(),
'Twilight',
'Stephenie Meyer',
'Romance',
'A supernatural romance between a human girl and a vampire.',
'9780316015844'),

(gen_random_uuid(),
'The Fault in Our Stars',
'John Green',
'Romance',
'A touching story about love, illness, and meaning.',
'9780142424179'),

(gen_random_uuid(),
'Call Me by Your Name',
'André Aciman',
'Romance',
'A lyrical coming-of-age love story set in Italy.',
'9781250169440'),

(gen_random_uuid(),
'Love, Rosie',
'Cecelia Ahern',
'Romance',
'A story of missed chances and enduring love told through letters.',
'9780786890753'),

(gen_random_uuid(),
'Eleanor & Park',
'Rainbow Rowell',
'Romance',
'A tender young-adult romance about first love.',
'9781250012579'),

(gen_random_uuid(),
'The Rosie Project',
'Graeme Simsion',
'Romance',
'A socially awkward professor designs a questionnaire to find love.',
'9781476729091'),

(gen_random_uuid(),
'One Day',
'David Nicholls',
'Romance',
'A couple reconnects on the same day each year.',
'9780340896983'),

(gen_random_uuid(),
'Normal People',
'Sally Rooney',
'Romance',
'A raw and intimate portrayal of love and emotional complexity.',
'9781984822178'),

(gen_random_uuid(),
'The Hating Game',
'Sally Thorne',
'Romance',
'A workplace enemies-to-lovers romantic comedy.',
'9780062439598');
INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Atomic Habits',
'James Clear',
'Self-Help',
'A practical guide on how small habits lead to remarkable results through consistency and systems.',
'9780735211292'),

(gen_random_uuid(),
'The Power of Now',
'Eckhart Tolle',
'Self-Help',
'A spiritual guide to living fully in the present moment.',
'9781577314806'),

(gen_random_uuid(),
'Think and Grow Rich',
'Napoleon Hill',
'Self-Help',
'A classic book on mindset, success, and personal achievement.',
'9781585424337'),

(gen_random_uuid(),
'The 7 Habits of Highly Effective People',
'Stephen R. Covey',
'Self-Help',
'A principle-centered approach to personal and professional effectiveness.',
'9781982137274'),

(gen_random_uuid(),
'How to Win Friends and Influence People',
'Dale Carnegie',
'Self-Help',
'Timeless advice on communication, leadership, and relationships.',
'9780671027032'),

(gen_random_uuid(),
'Man’s Search for Meaning',
'Viktor E. Frankl',
'Self-Help',
'A Holocaust survivor reflects on meaning, suffering, and purpose.',
'9780807014271'),

(gen_random_uuid(),
'Deep Work',
'Cal Newport',
'Self-Help',
'Strategies for focused success in a distracted world.',
'9781455586691'),

(gen_random_uuid(),
'The Subtle Art of Not Giving a F*ck',
'Mark Manson',
'Self-Help',
'A counterintuitive approach to living a meaningful life.',
'9780062457714'),

(gen_random_uuid(),
'You Are a Badass',
'Jen Sincero',
'Self-Help',
'A motivational guide to confidence and self-belief.',
'9780762447695'),

(gen_random_uuid(),
'Awaken the Giant Within',
'Tony Robbins',
'Self-Help',
'Strategies for mastering emotions, finances, and life.',
'9780671791544'),

(gen_random_uuid(),
'Mindset',
'Carol S. Dweck',
'Self-Help',
'How growth mindset shapes success.',
'9780345472328'),

(gen_random_uuid(),
'The Four Agreements',
'Don Miguel Ruiz',
'Self-Help',
'Ancient Toltec wisdom for personal freedom.',
'9781878424310'),

(gen_random_uuid(),
'Grit',
'Angela Duckworth',
'Self-Help',
'Why passion and perseverance matter more than talent.',
'9781501111105'),

(gen_random_uuid(),
'Essentialism',
'Greg McKeown',
'Self-Help',
'The disciplined pursuit of less but better.',
'9780804137386'),

(gen_random_uuid(),
'Can’t Hurt Me',
'David Goggins',
'Self-Help',
'A memoir about mental toughness and discipline.',
'9781544512280');
INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'The Lean Startup',
'Eric Ries',
'Business',
'Introduces a scientific approach to building startups through validated learning, experimentation, and rapid iteration. Widely used by founders to reduce waste and build products customers actually want.',
'9780307887894'),

(gen_random_uuid(),
'Zero to One',
'Peter Thiel',
'Business',
'Explores how to build companies that create entirely new value rather than competing in existing markets. Emphasizes innovation, monopolies, and long-term thinking.',
'9780804139298'),

(gen_random_uuid(),
'Good to Great',
'Jim Collins',
'Business',
'Based on extensive research, this book explains how average companies can transform into exceptional ones through disciplined leadership and culture.',
'9780066620992'),

(gen_random_uuid(),
'The Hard Thing About Hard Things',
'Ben Horowitz',
'Business',
'A brutally honest guide to running a company, covering difficult decisions, layoffs, and leadership challenges rarely discussed.',
'9780062273208'),

(gen_random_uuid(),
'Start with Why',
'Simon Sinek',
'Business',
'Argues that great leaders and organizations inspire action by clearly communicating their purpose and beliefs.',
'9781591846444'),

(gen_random_uuid(),
'Built to Last',
'Jim Collins & Jerry I. Porras',
'Business',
'Examines visionary companies that have endured for decades and identifies principles behind their sustained success.',
'9780060516406'),

(gen_random_uuid(),
'The Innovator’s Dilemma',
'Clayton M. Christensen',
'Business',
'Explains why successful companies fail to innovate and how disruptive technologies reshape industries.',
'9780062060242'),

(gen_random_uuid(),
'Measure What Matters',
'John Doerr',
'Business',
'Introduces OKRs (Objectives and Key Results), a goal-setting framework used by companies like Google and Intel.',
'9780525536222'),

(gen_random_uuid(),
'Blue Ocean Strategy',
'W. Chan Kim & Renée Mauborgne',
'Business',
'Encourages businesses to create uncontested market spaces instead of competing in saturated industries.',
'9781625274496'),

(gen_random_uuid(),
'Thinking, Fast and Slow',
'Daniel Kahneman',
'Business',
'Explores how humans make decisions using two systems of thinking, influencing economics, business, and behavior.',
'9780374533557'),

(gen_random_uuid(),
'The E-Myth Revisited',
'Michael E. Gerber',
'Business',
'Challenges common assumptions about small businesses and explains why systems matter more than passion alone.',
'9780887307287'),

(gen_random_uuid(),
'Leaders Eat Last',
'Simon Sinek',
'Business',
'Discusses how strong leadership creates trust, cooperation, and long-term success within organizations.',
'9781591845324'),

(gen_random_uuid(),
'The Art of Strategy',
'Avinash K. Dixit & Barry J. Nalebuff',
'Business',
'Applies game theory concepts to real-world business and competitive situations.',
'9780393337174'),

(gen_random_uuid(),
'Delivering Happiness',
'Tony Hsieh',
'Business',
'A memoir and business philosophy centered on customer service, culture, and happiness at Zappos.',
'9780446576222'),

(gen_random_uuid(),
'Principles',
'Ray Dalio',
'Business',
'Outlines life and work principles developed while building one of the world’s most successful hedge funds.',
'9781501124020'),

(gen_random_uuid(),
'The Personal MBA',
'Josh Kaufman',
'Business',
'Teaches core business concepts without needing a traditional MBA program.',
'9781591845577'),

(gen_random_uuid(),
'Who Moved My Cheese?',
'Spencer Johnson',
'Business',
'A simple parable about dealing with change in work and life.',
'9780091816971'),

(gen_random_uuid(),
'Crossing the Chasm',
'Geoffrey A. Moore',
'Business',
'Focuses on marketing and selling disruptive products to mainstream customers.',
'9780062292988'),

(gen_random_uuid(),
'The Millionaire Next Door',
'Thomas J. Stanley & William D. Danko',
'Business',
'Explores the habits and behaviors of wealthy individuals who live modestly.',
'9781589795471'),

(gen_random_uuid(),
'No Rules Rules',
'Reed Hastings & Erin Meyer',
'Business',
'Describes Netflix’s unconventional culture and management philosophy.',
'9781984877864');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Clean Code',
'Robert C. Martin',
'Technology',
'A handbook of best practices for writing readable, maintainable, and professional software.',
'9780132350884'),

(gen_random_uuid(),
'Design Patterns',
'Erich Gamma et al.',
'Technology',
'Introduces reusable solutions to common software design problems.',
'9780201633610'),

(gen_random_uuid(),
'Refactoring',
'Martin Fowler',
'Technology',
'Explains techniques for improving existing code without changing its behavior.',
'9780134757599'),

(gen_random_uuid(),
'The Pragmatic Programmer',
'Andrew Hunt & David Thomas',
'Technology',
'A classic guide on software craftsmanship, mindset, and best practices.',
'9780135957059'),

(gen_random_uuid(),
'Clean Architecture',
'Robert C. Martin',
'Technology',
'Provides guidance on building scalable and maintainable software systems.',
'9780134494166'),

(gen_random_uuid(),
'You Don’t Know JS Yet',
'Kyle Simpson',
'Technology',
'A deep dive into JavaScript fundamentals and behavior.',
'9781091210090'),

(gen_random_uuid(),
'Introduction to Algorithms',
'Thomas H. Cormen et al.',
'Technology',
'A comprehensive academic reference on algorithms and data structures.',
'9780262046305'),

(gen_random_uuid(),
'System Design Interview',
'Alex Xu',
'Technology',
'Practical guidance for designing large-scale distributed systems.',
'9781736049112'),

(gen_random_uuid(),
'Code Complete',
'Steve McConnell',
'Technology',
'A practical handbook of software construction techniques.',
'9780735619678'),

(gen_random_uuid(),
'Head First Design Patterns',
'Eric Freeman et al.',
'Technology',
'Uses a visual and engaging approach to explain software design patterns.',
'9780596007126'),

(gen_random_uuid(),
'Effective Java',
'Joshua Bloch',
'Technology',
'Best practices for writing robust and maintainable Java code.',
'9780134685991'),

(gen_random_uuid(),
'Domain-Driven Design',
'Eric Evans',
'Technology',
'Focuses on aligning software design with complex business domains.',
'9780321125217'),

(gen_random_uuid(),
'Release It!',
'Michael T. Nygard',
'Technology',
'Discusses stability patterns for production-ready systems.',
'9781680502398'),

(gen_random_uuid(),
'Building Microservices',
'Sam Newman',
'Technology',
'Explores principles and practices for microservice architecture.',
'9781492034025'),

(gen_random_uuid(),
'Site Reliability Engineering',
'Google',
'Technology',
'Introduces SRE practices for building reliable large-scale systems.',
'9781491929124');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Influence',
'Robert B. Cialdini',
'Psychology',
'Explains the psychology behind persuasion and why people say yes.',
'9780062937650'),

(gen_random_uuid(),
'Thinking, Fast and Slow',
'Daniel Kahneman',
'Psychology',
'A deep exploration of human decision-making and cognitive bias.',
'9780374533557'),

(gen_random_uuid(),
'Emotional Intelligence',
'Daniel Goleman',
'Psychology',
'Demonstrates how emotional awareness is as important as IQ for success.',
'9780553383713'),

(gen_random_uuid(),
'Predictably Irrational',
'Dan Ariely',
'Psychology',
'Explores the hidden forces that shape our decisions.',
'9780061353246'),

(gen_random_uuid(),
'Flow',
'Mihaly Csikszentmihalyi',
'Psychology',
'Explains the psychology of optimal experience and happiness.',
'9780061339202'),

(gen_random_uuid(),
'The Body Keeps the Score',
'Bessel van der Kolk',
'Psychology',
'Explores trauma and how it reshapes the brain and body.',
'9780143127741'),

(gen_random_uuid(),
'Quiet',
'Susan Cain',
'Psychology',
'A powerful look at introversion and its strengths.',
'9780307352156'),

(gen_random_uuid(),
'Drive',
'Daniel H. Pink',
'Psychology',
'Examines what truly motivates people beyond money and rewards.',
'9781594484803'),

(gen_random_uuid(),
'Blink',
'Malcolm Gladwell',
'Psychology',
'Explores the power and pitfalls of rapid decision-making.',
'9780316010665'),

(gen_random_uuid(),
'Games People Play',
'Eric Berne',
'Psychology',
'Analyzes social interactions and psychological games people engage in.',
'9780345410030'),

(gen_random_uuid(),
'Attached',
'Amir Levine & Rachel Heller',
'Psychology',
'Explains adult attachment styles and romantic relationships.',
'9781585429134'),

(gen_random_uuid(),
'Thinking in Bets',
'Annie Duke',
'Psychology',
'Applies decision-making psychology to uncertainty and risk.',
'9780735216358'),

(gen_random_uuid(),
'Man and His Symbols',
'Carl Jung',
'Psychology',
'Explores the role of symbols and the unconscious mind.',
'9780440351832'),

(gen_random_uuid(),
'The Social Animal',
'Elliot Aronson',
'Psychology',
'An accessible introduction to social psychology.',
'9780716729032'),

(gen_random_uuid(),
'Behave',
'Robert Sapolsky',
'Psychology',
'Examines human behavior through biology, psychology, and culture.',
'9781594205073');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Sapiens',
'Yuval Noah Harari',
'History',
'A sweeping history of humankind, exploring how biology, culture, and shared myths shaped modern society. It connects ancient history with contemporary global challenges.',
'9780062316097'),

(gen_random_uuid(),
'Guns, Germs, and Steel',
'Jared Diamond',
'History',
'Examines why some civilizations advanced faster than others, focusing on geography, environment, and access to resources rather than race or intelligence.',
'9780393317558'),

(gen_random_uuid(),
'A People’s History of the United States',
'Howard Zinn',
'History',
'Recounts American history from the perspective of marginalized groups, challenging traditional historical narratives.',
'9780062397348'),

(gen_random_uuid(),
'The Silk Roads',
'Peter Frankopan',
'History',
'Reframes world history by focusing on trade routes that connected East and West for centuries.',
'9781101912379'),

(gen_random_uuid(),
'Team of Rivals',
'Doris Kearns Goodwin',
'History',
'Explores Abraham Lincoln’s leadership through his relationships with political rivals during the Civil War.',
'9780743270755'),

(gen_random_uuid(),
'The Wright Brothers',
'David McCullough',
'History',
'The story of the brothers who invented powered flight, highlighting perseverance and innovation.',
'9781476728742'),

(gen_random_uuid(),
'Postwar',
'Tony Judt',
'History',
'A comprehensive history of Europe after World War II, examining political, social, and economic changes.',
'9780143037750'),

(gen_random_uuid(),
'The Rise and Fall of the Third Reich',
'William L. Shirer',
'History',
'A detailed account of Nazi Germany based on firsthand reporting and historical documents.',
'9781451651683'),

(gen_random_uuid(),
'India After Gandhi',
'Ramachandra Guha',
'History',
'A definitive account of India’s political and social evolution after independence.',
'9780330505543'),

(gen_random_uuid(),
'The Cold War',
'John Lewis Gaddis',
'History',
'An accessible overview of Cold War politics and global tensions.',
'9780143038276'),

(gen_random_uuid(),
'SPQR',
'Mary Beard',
'History',
'A richly detailed history of ancient Rome, from its origins to empire.',
'9781631492228'),

(gen_random_uuid(),
'The Crusades',
'Thomas Asbridge',
'History',
'A balanced and modern history of the medieval Crusades.',
'9780060787295'),

(gen_random_uuid(),
'Gandhi: An Autobiography',
'Mahatma Gandhi',
'History',
'Gandhi’s reflections on truth, nonviolence, and his life’s journey.',
'9780807059098'),

(gen_random_uuid(),
'The Discovery of India',
'Jawaharlal Nehru',
'History',
'A reflection on India’s history, culture, and identity written during imprisonment.',
'9780143031031'),

(gen_random_uuid(),
'The Romanovs',
'Simon Sebag Montefiore',
'History',
'A dramatic history of Russia’s ruling dynasty.',
'9780307266521'),

(gen_random_uuid(),
'The Age of Extremes',
'Eric Hobsbawm',
'History',
'A global history of the short twentieth century from World War I to the Cold War.',
'9780679730057'),

(gen_random_uuid(),
'The Holocaust',
'Laurence Rees',
'History',
'A comprehensive examination of the Holocaust and its perpetrators.',
'9781586483579'),

(gen_random_uuid(),
'1491',
'Charles C. Mann',
'History',
'Reveals the complexity of the Americas before European contact.',
'9781400032051'),

(gen_random_uuid(),
'The Penguin History of the World',
'J.M. Roberts',
'History',
'A single-volume global history from ancient times to the modern era.',
'9780141002514'),

(gen_random_uuid(),
'Empire',
'Niall Ferguson',
'History',
'Analyzes the rise and consequences of the British Empire.',
'9780465019485');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Meditations',
'Marcus Aurelius',
'Philosophy',
'Personal reflections by a Roman emperor on virtue, discipline, and the nature of life.',
'9780140449334'),

(gen_random_uuid(),
'The Republic',
'Plato',
'Philosophy',
'A foundational work discussing justice, morality, and the ideal state.',
'9780140455113'),

(gen_random_uuid(),
'Beyond Good and Evil',
'Friedrich Nietzsche',
'Philosophy',
'A critique of traditional morality and philosophy.',
'9780140449235'),

(gen_random_uuid(),
'Being and Nothingness',
'Jean-Paul Sartre',
'Philosophy',
'A cornerstone of existentialist philosophy focusing on freedom and responsibility.',
'9780671867805'),

(gen_random_uuid(),
'Thus Spoke Zarathustra',
'Friedrich Nietzsche',
'Philosophy',
'A poetic exploration of self-overcoming and individual meaning.',
'9780140441185'),

(gen_random_uuid(),
'The Art of War',
'Sun Tzu',
'Philosophy',
'An ancient treatise on strategy, leadership, and conflict.',
'9781599869773'),

(gen_random_uuid(),
'Letters from a Stoic',
'Seneca',
'Philosophy',
'Practical wisdom on ethics, suffering, and resilience.',
'9780140442106'),

(gen_random_uuid(),
'The Myth of Sisyphus',
'Albert Camus',
'Philosophy',
'An exploration of absurdity and the human search for meaning.',
'9780679733737'),

(gen_random_uuid(),
'Critique of Pure Reason',
'Immanuel Kant',
'Philosophy',
'A groundbreaking examination of human reason and knowledge.',
'9780140447477'),

(gen_random_uuid(),
'Being Mortal',
'Atul Gawande',
'Philosophy',
'Examines mortality, medicine, and dignity at the end of life.',
'9780805095159'),

(gen_random_uuid(),
'The Consolation of Philosophy',
'Boethius',
'Philosophy',
'A reflection on fortune, happiness, and suffering.',
'9780140447804'),

(gen_random_uuid(),
'Zen and the Art of Motorcycle Maintenance',
'Robert M. Pirsig',
'Philosophy',
'A philosophical journey blending technology, values, and meaning.',
'9780060589462'),

(gen_random_uuid(),
'The Problems of Philosophy',
'Bertrand Russell',
'Philosophy',
'An introduction to philosophical inquiry and critical thinking.',
'9780192854230'),

(gen_random_uuid(),
'An Enquiry Concerning Human Understanding',
'David Hume',
'Philosophy',
'A key work in empiricism and skepticism.',
'9780198245360'),

(gen_random_uuid(),
'The Tao Te Ching',
'Laozi',
'Philosophy',
'A foundational text of Taoism emphasizing harmony and simplicity.',
'9780140441314');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Dune',
'Frank Herbert',
'Science Fiction',
'An epic science fiction saga exploring politics, ecology, and power on the desert planet Arrakis.',
'9780441172719'),

(gen_random_uuid(),
'Foundation',
'Isaac Asimov',
'Science Fiction',
'A grand narrative about the fall and rebirth of civilizations.',
'9780553293357'),

(gen_random_uuid(),
'Neuromancer',
'William Gibson',
'Science Fiction',
'A cyberpunk classic that shaped modern science fiction.',
'9780441569595'),

(gen_random_uuid(),
'Ender’s Game',
'Orson Scott Card',
'Science Fiction',
'A young genius is trained for interstellar war.',
'9780812550702'),

(gen_random_uuid(),
'The Left Hand of Darkness',
'Ursula K. Le Guin',
'Science Fiction',
'Explores gender, politics, and identity on a distant planet.',
'9780441478125'),

 

(gen_random_uuid(),
'Long Walk to Freedom',
'Nelson Mandela',
'Biography',
'Mandela’s autobiography detailing his struggle against apartheid.',
'9780316548182'),

(gen_random_uuid(),
'Einstein: His Life and Universe',
'Walter Isaacson',
'Biography',
'Explores Einstein’s scientific genius and personal life.',
'9780743264747'),

(gen_random_uuid(),
'Becoming',
'Michelle Obama',
'Biography',
'A deeply personal memoir of identity, family, and leadership.',
'9781524763138'),

(gen_random_uuid(),
'The Diary of a Young Girl',
'Anne Frank',
'Biography',
'A firsthand account of life hiding during the Holocaust.',
'9780553296983'),

(gen_random_uuid(),
'Elon Musk',
'Ashlee Vance',
'Biography',
'The life and ambitions of the entrepreneur behind Tesla and SpaceX.',
'9780062301239'),

(gen_random_uuid(),
'I Am Malala',
'Malala Yousafzai',
'Biography',
'The story of a young girl’s fight for education and freedom.',
'9780316322409'),

(gen_random_uuid(),
'The Martian',
'Andy Weir',
'Science Fiction',
'A stranded astronaut uses science and ingenuity to survive on Mars.',
'9780553418026'),

(gen_random_uuid(),
'Brave New World',
'Aldous Huxley',
'Science Fiction',
'A dystopian vision of a controlled, pleasure-driven society.',
'9780060850524'),

(gen_random_uuid(),
'1984',
'George Orwell',
'Science Fiction',
'A chilling portrayal of totalitarian surveillance and control.',
'9780451524935');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'East of Eden',
'John Steinbeck',
'Classic',
'A multi-generational novel retelling the biblical story of Cain and Abel, exploring good and evil, free will, and family legacy.',
'9780142004234'),

(gen_random_uuid(),
'The Grapes of Wrath',
'John Steinbeck',
'Classic',
'Follows a displaced farming family during the Great Depression, capturing social injustice, dignity, and survival.',
'9780143039439'),

(gen_random_uuid(),
'Of Mice and Men',
'John Steinbeck',
'Classic',
'A tragic story of friendship and shattered dreams during the Great Depression.',
'9780140177398'),

(gen_random_uuid(),
'The Old Man and the Sea',
'Ernest Hemingway',
'Classic',
'A short yet powerful novel about perseverance, pride, and the struggle between man and nature.',
'9780684801223'),

(gen_random_uuid(),
'A Farewell to Arms',
'Ernest Hemingway',
'Classic',
'A love story set during World War I that explores loss, war, and emotional resilience.',
'9780684801469'),

(gen_random_uuid(),
'Lord of the Flies',
'William Golding',
'Classic',
'A group of boys stranded on an island descends into savagery, revealing the darkness within human nature.',
'9780399501487'),

(gen_random_uuid(),
'Catch-22',
'Joseph Heller',
'Classic',
'A satirical novel about the absurdity of war and bureaucratic logic.',
'9781451626650'),

(gen_random_uuid(),
'Animal Farm',
'George Orwell',
'Classic',
'A political allegory critiquing totalitarianism through a farmyard revolution.',
'9780451526342'),

(gen_random_uuid(),
'The Bell Jar',
'Sylvia Plath',
'Classic',
'A semi-autobiographical novel depicting mental illness and identity struggles.',
'9780060837020'),

(gen_random_uuid(),
'Slaughterhouse-Five',
'Kurt Vonnegut',
'Classic',
'A darkly humorous anti-war novel blending time travel and trauma.',
'9780385333849'),

(gen_random_uuid(),
'The Sound and the Fury',
'William Faulkner',
'Classic',
'A complex narrative portraying the decline of a Southern family.',
'9780679732242'),

(gen_random_uuid(),
'One Hundred Years of Solitude',
'Gabriel García Márquez',
'Classic',
'A landmark work of magical realism chronicling generations of the Buendía family.',
'9780060883287'),

(gen_random_uuid(),
'The Trial',
'Franz Kafka',
'Classic',
'A man is arrested for an unknown crime, symbolizing bureaucratic oppression.',
'9780805210408'),

(gen_random_uuid(),
'Middlemarch',
'George Eliot',
'Classic',
'A richly detailed portrait of provincial English life and moral complexity.',
'9780141439549'),

(gen_random_uuid(),
'Don Quixote',
'Miguel de Cervantes',
'Classic',
'A satirical tale of idealism, madness, and heroism.',
'9780060934347');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'The Handmaid’s Tale',
'Margaret Atwood',
'Fiction',
'A dystopian novel exploring control, gender oppression, and resistance.',
'9780385490818'),

 

(gen_random_uuid(),
'The Underground Railroad',
'Colson Whitehead',
'Fiction',
'A reimagined history of slavery through magical realism.',
'9780385542364'),

(gen_random_uuid(),
'The Hunger Games',
'Suzanne Collins',
'Fiction',
'A dystopian survival story centered on rebellion and sacrifice.',
'9780439023481'),

(gen_random_uuid(),
'The Catcher in the Rye',
'J.D. Salinger',
'Fiction',
'A teenage boy’s rebellion against adult hypocrisy.',
'9780316769488'),

(gen_random_uuid(),
'The Girl Who Drank the Moon',
'Kelly Barnhill',
'Fiction',
'A fantasy-infused tale about magic, sacrifice, and love.',
'9781616205676'),

(gen_random_uuid(),
'The Book of Negroes',
'Lawrence Hill',
'Fiction',
'A powerful historical novel about slavery and identity.',
'9780393339642'),

(gen_random_uuid(),
'The Shadowhunter Chronicles',
'Cassandra Clare',
'Fiction',
'A modern fantasy saga of demons, angels, and hidden worlds.',
'9781416955078'),

 

(gen_random_uuid(),
'The Road Back',
'Erich Maria Remarque',
'Fiction',
'A portrayal of soldiers returning from World War I.',
'9780449213940'),

(gen_random_uuid(),
'The Giver',
'Lois Lowry',
'Fiction',
'A young boy uncovers the truth behind a seemingly perfect society.',
'9780544336261'),

(gen_random_uuid(),
'Life of Pi',
'Yann Martel',
'Fiction',
'A philosophical survival tale involving faith and storytelling.',
'9780156027328'),

(gen_random_uuid(),
'American Dirt',
'Jeanine Cummins',
'Fiction',
'A mother and son flee cartel violence in Mexico.',
'9781250209764'),

(gen_random_uuid(),
'The Perks of Being a Wallflower',
'Stephen Chbosky',
'Fiction',
'A coming-of-age novel about friendship, trauma, and self-discovery.',
'9780671027346'),

(gen_random_uuid(),
'The Light We Lost',
'Jill Santopolo',
'Fiction',
'A love story shaped by timing and fate.',
'9780735212759');

INSERT INTO books (id, title, author, genre, description, isbn) VALUES
(gen_random_uuid(),
'Man’s Search for Meaning',
'Viktor E. Frankl',
'Non-Fiction',
'A Holocaust survivor reflects on purpose, suffering, and resilience.',
'9780807014271'),

(gen_random_uuid(),
'The Immortal Life of Henrietta Lacks',
'Rebecca Skloot',
'Non-Fiction',
'Explores ethics, race, and medical science.',
'9781400052189'),

(gen_random_uuid(),
'Into the Wild',
'Jon Krakauer',
'Non-Fiction',
'A true story of freedom, idealism, and tragedy.',
'9780385486804'),

(gen_random_uuid(),
'Educated',
'Tara Westover',
'Memoir',
'A woman’s journey from an isolated upbringing to higher education.',
'9780399590504'),

(gen_random_uuid(),
'When Breath Becomes Air',
'Paul Kalanithi',
'Memoir',
'A neurosurgeon confronts mortality and meaning.',
'9780812988406'),

(gen_random_uuid(),
'Born a Crime',
'Trevor Noah',
'Memoir',
'A humorous and poignant memoir of growing up in apartheid South Africa.',
'9780399588198'),

(gen_random_uuid(),
'The Art of Happiness',
'Dalai Lama',
'Non-Fiction',
'A blend of psychology and Buddhist philosophy.',
'9781573221115'),

(gen_random_uuid(),
'Quiet',
'Susan Cain',
'Non-Fiction',
'Explores the power of introverts in society.',
'9780307352156'),

(gen_random_uuid(),
'Outliers',
'Malcolm Gladwell',
'Non-Fiction',
'Examines factors behind extraordinary success.',
'9780316017930'),

(gen_random_uuid(),
'Freakonomics',
'Steven D. Levitt & Stephen J. Dubner',
'Non-Fiction',
'Uses economics to explore hidden patterns in society.',
'9780060731335'),

(gen_random_uuid(),
'The Tipping Point',
'Malcolm Gladwell',
'Non-Fiction',
'How small actions can create big change.',
'9780316346627'),

(gen_random_uuid(),
'The Wright Brothers',
'David McCullough',
'Biography',
'The story of innovation, perseverance, and flight.',
'9781476728759'),

(gen_random_uuid(),
'Steve Jobs',
'Walter Isaacson',
'Biography',
'A detailed biography of Apple’s co-founder.',
'9781451648539'),

(gen_random_uuid(),
'Into Thin Air',
'Jon Krakauer',
'Non-Fiction',
'A firsthand account of the Mount Everest disaster.',
'9780385494786'),

(gen_random_uuid(),
'The Power Broker',
'Robert A. Caro',
'Biography',
'An exploration of political power and urban development.',
'9780394720241'),

(gen_random_uuid(),
'The Diary of a Young Girl',
'Anne Frank',
'Memoir',
'A young girl’s reflections during the Holocaust.',
'9780553296983'),

(gen_random_uuid(),
'Night',
'Elie Wiesel',
'Memoir',
'A harrowing account of Holocaust survival.',
'9780374500015'),

(gen_random_uuid(),
'The Sixth Extinction',
'Elizabeth Kolbert',
'Non-Fiction',
'Explores humanity’s role in mass extinction.',
'9781250062185'),

(gen_random_uuid(),
'Atomic Habits',
'James Clear',
'Non-Fiction',
'How small changes create remarkable results.',
'9780735211292'),

(gen_random_uuid(),
'Thinking, Fast and Slow',
'Daniel Kahneman',
'Non-Fiction',
'Explains how cognitive biases shape decisions.',
'9780374533557');



  
